repos:
- repo: https://github.com/AFPy/powrap
  rev: v1.0.0
  hooks:
  - id: powrap
- repo: https://github.com/AFPy/pospell
  rev: v1.1
  hooks:
  - id: pospell
    args: [--language, fr, -p, .pospell.dic ]